import { Dimensions, StyleSheet } from "react-native";
import Colors from './Colors'

const fontFamily = 'open-sans';
const fontFamilyBold = 'open-sans-bold';

const Styles = StyleSheet.create({
  fontFamily: { fontFamily },
  fontFamilyBold: { fontFamily: fontFamilyBold },

  margin0: { margin: 0 },
  margin5: { margin: 5 },
  marginT0: { marginTop: 0 },
  marginL0: { marginLeft: 0 },
  marginR0: { marginRight: 0 },
  marginB0: { marginBottom: 0 },
  marginT5: { marginTop: 5 },
  marginB5: { marginBottom: 5 },
  marginL5: { marginLeft: 5 },
  marginR5: { marginRight: 5 },
  margin10: { margin: 10 },
  marginT10: { marginTop: 10 },
  marginB10: { marginBottom: 10 },
  marginL10: { marginLeft: 10 },
  marginR10: { marginRight: 10 },
  margin15: { margin: 15 },
  marginT15: { marginTop: 15 },
  marginB15: { marginBottom: 15 },
  marginL15: { marginLeft: 15 },
  marginR15: { marginRight: 15 },
  margin20: { margin: 20 },
  marginT20: { marginTop: 20 },
  marginB20: { marginBottom: 20 },
  marginL20: { marginLeft: 20 },
  marginR20: { marginRight: 20 },
  padding0: { padding: 0 },
  paddingT0: { paddingTop: 0 },
  paddingB0: { paddingBottom: 0 },
  paddingL0: { paddingLeft: 0 },
  paddingR0: { paddingRight: 0 },
  padding5: { padding: 5 },
  paddingT5: { paddingTop: 5 },
  paddingB5: { paddingBottom: 5 },
  paddingL5: { paddingLeft: 5 },
  paddingR5: { paddingRight: 5 },
  padding10: { padding: 10 },
  paddingT10: { paddingTop: 10 },
  paddingB10: { paddingBottom: 10 },
  paddingL10: { paddingLeft: 10 },
  paddingR10: { paddingRight: 10 },
  padding15: { padding: 15 },
  paddingT15: { paddingTop: 15 },
  paddingB15: { paddingBottom: 15 },
  paddingL15: { paddingLeft: 15 },
  paddingR15: { paddingRight: 15 },
  padding20: { padding: 20 },
  paddingT20: { paddingTop: 20 },
  paddingB20: { paddingBottom: 20 },
  paddingL20: { paddingLeft: 20 },
  paddingR20: { paddingRight: 20 },

  headerTitleStyle: { fontFamily: fontFamilyBold, color: Colors.defaultText, fontSize: 17 },
  textDefault: { fontFamily, color: Colors.defaultText },
  text10: { fontFamily, fontSize: 10, color: Colors.defaultText },
  text11: { fontFamily, fontSize: 11, color: Colors.defaultText },
  text12: { fontFamily, fontSize: 12, color: Colors.defaultText },
  text13: { fontFamily, fontSize: 13, color: Colors.defaultText },
  text14: { fontFamily, fontSize: 14, color: Colors.defaultText },
  text15: { fontFamily, fontSize: 15, color: Colors.defaultText },
  text16: { fontFamily, fontSize: 16, color: Colors.defaultText },
  text17: { fontFamily, fontSize: 17, color: Colors.defaultText },
  text18: { fontFamily, fontSize: 18, color: Colors.defaultText },
  text20: { fontFamily, fontSize: 20, color: Colors.defaultText },
  text22: { fontFamily, fontSize: 22, color: Colors.defaultText },
  text24: { fontFamily, fontSize: 24, color: Colors.defaultText },
  text26: { fontFamily, fontSize: 26, color: Colors.defaultText },
  text28: { fontFamily, fontSize: 28, color: Colors.defaultText },
  text35: { fontFamily, fontSize: 35, color: Colors.defaultText },
  text40: { fontFamily, fontSize: 40, color: Colors.defaultText },

  textRegular: { fontFamily: fontFamily, color: Colors.defaultText },
  textBold: { fontFamily: fontFamilyBold, color: Colors.defaultText },
  textRight: { textAlign: 'right' },
  textCenter: { textAlign: 'center' },
  textJustify: { textAlign: 'justify' },
  textWhite: { color: 'white' },
  textPrimary: { color: Colors.primaryColor },
  textLightText: { color: Colors.lightText },
  textRed: { color: Colors.red },
  textGreen: { color: Colors.green },
  textGray: { color: Colors.gray },
  textEmpty: { fontFamily, fontSize: 14, color: Colors.lightText, textAlign: 'center' },

  btnWhite: { borderWidth: 1, borderColor: Colors.background, backgroundColor: 'white' },
  btnGreen: { borderWidth: 1, borderColor: Colors.green, backgroundColor: Colors.green },
  btnPrimary: { borderWidth: 1, borderColor: Colors.primaryColor, backgroundColor: Colors.primaryColor },
  btnBorderWhite: { borderWidth: 1, borderColor: 'white' },
  btnBorderPrimary: { borderWidth: 1, borderColor: Colors.primaryColor },
  btnBorderRed: { borderWidth: 1, borderColor: Colors.red },
  btnBorderGreen: { borderWidth: 1, borderColor: Colors.green },
  btnBorderDF: { borderWidth: 1, borderColor: Colors.defaultText },
  btnBorderLF: { borderWidth: 1, borderColor: Colors.lightText },
  
  spaceAround: { justifyContent: 'space-around' },
  spaceBetween: { justifyContent: 'space-between' },
  center: { alignItems: 'center', justifyContent: 'center' },
  viewCenter: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  inline: { flexDirection: 'row', flexWrap: 'wrap' },
  cardRounded: { margin: 0, backgroundColor: 'white', borderWidth: 0, borderRadius: 4, overflow: 'hidden' },
  cardLevel: { margin: 0, backgroundColor: 'white', borderWidth: StyleSheet.hairlineWidth, borderColor: Colors.gray },

  input: { fontSize: 17, color: Colors.lightText, padding: 5, paddingLeft: 0, paddingRight: 0 },
  inputView: { borderBottomColor: Colors.gray, borderBottomWidth: StyleSheet.hairlineWidth },
  inputText: { fontSize: 17, color: Colors.lightText, padding: 5, paddingLeft: 0, paddingRight: 0, borderBottomColor: Colors.gray, borderBottomWidth: StyleSheet.hairlineWidth },
  inputMultiline: { fontSize: 16, color: Colors.lightText, borderColor: Colors.gray, borderWidth: StyleSheet.hairlineWidth, minHeight: 100 },

  viewDivider15: { height: 15 },
  viewDivider: { height: 10 },
  viewDivider5: { height: 5 },
  viewDividerLine: { height: StyleSheet.hairlineWidth, width: '100%', borderBottomColor: Colors.gray, borderBottomWidth: StyleSheet.hairlineWidth }
});

export default Styles;
